language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra
    - extra-android-support

script:
    - ./gradlew test

# http://docs.travis-ci.com/user/migrating-from-legacy/#tl%3Bdr
sudo: false
